#!/command/with-contenv bash

openwakeword_bootstrap_filesystem() {
    if [ ! -d "${OPENWAKEWORD_DATA_PATH}" ]; then
        mkdir -p "${OPENWAKEWORD_DATA_PATH}"
    fi
    if [ $(stat -c %G "${OPENWAKEWORD_DATA_PATH}") != "${OPENWAKEWORD_GROUP}" ] ; then chown "${OPENWAKEWORD_USER}":"${OPENWAKEWORD_GROUP}" "${OPENWAKEWORD_DATA_PATH}" ; fi

    if [ ! -d "${OPENWAKEWORD_MODEL_PATH}" ]; then
        mkdir -p "${OPENWAKEWORD_MODEL_PATH}"
    fi
    if [ $(stat -c %U "${OPENWAKEWORD_MODEL_PATH}") != "${OPENWAKEWORD_USER}" ] ; then chown -R "${OPENWAKEWORD_USER}":"${OPENWAKEWORD_GROUP}" "${OPENWAKEWORD_MODEL_PATH}" ; fi

    if [ ! -d "${OPENWAKEWORD_OUTPUT_PATH}" ]; then
        mkdir -p "${OPENWAKEWORD_OUTPUT_PATH}"
    fi
    if [ $(stat -c %U "${OPENWAKEWORD_OUTPUT_PATH}") != "${OPENWAKEWORD_USER}" ] ; then chown -R "${OPENWAKEWORD_USER}":"${OPENWAKEWORD_GROUP}" "${OPENWAKEWORD_OUTPUT_PATH}" ; fi

    if [ ! -d "${OPENWAKEWORD_LOG_PATH}" ]; then
        mkdir -p "${OPENWAKEWORD_LOG_PATH}"
    fi
    if [ $(stat -c %U "${OPENWAKEWORD_LOG_PATH}") != "${OPENWAKEWORD_USER}" ] ; then chown -R "${OPENWAKEWORD_USER}":"${OPENWAKEWORD_GROUP}" "${OPENWAKEWORD_LOG_PATH}" ; fi

    case "${OPENWAKEWORD_LOG_TYPE,,}" in
        file | both)
            create_logrotate openwakeword "${OPENWAKEWORD_LOG_PATH}"/"${OPENWAKEWORD_LOG_FILE}" openwakeword "${OPENWAKEWORD_USER}" "${OPENWAKEWORD_GROUP}"
        ;;
    esac
}
