#!/command/with-contenv bash

piper_bootstrap_filesystem() {
    if [ ! -d "${PIPER_DATA_PATH}" ]; then
        mkdir -p "${PIPER_DATA_PATH}"
    fi
    if [ $(stat -c %G "${PIPER_DATA_PATH}") != "${PIPER_GROUP}" ] ; then chown "${PIPER_USER}":"${PIPER_GROUP}" "${PIPER_DATA_PATH}" ; fi

    if [ ! -d "${PIPER_LOG_PATH}" ]; then
        mkdir -p "${PIPER_LOG_PATH}"
    fi
    if [ $(stat -c %U "${PIPER_LOG_PATH}") != "${PIPER_USER}" ] ; then chown -R "${PIPER_USER}":"${PIPER_GROUP}" "${PIPER_LOG_PATH}" ; fi

    case "${PIPER_LOG_TYPE,,}" in
        file | both)
            create_logrotate piper "${PIPER_LOG_PATH}"/"${PIPER_LOG_FILE}" piper "${PIPER_USER}" "${PIPER_GROUP}"
        ;;
    esac
}