#!/command/with-contenv bash

whisper_bootstrap_filesystem() {
    if [ ! -d "${WHISPER_DATA_PATH}" ]; then
        mkdir -p "${WHISPER_DATA_PATH}"
    fi
    if [ $(stat -c %G "${WHISPER_DATA_PATH}") != "${WHISPER_GROUP}" ] ; then chown "${WHISPER_USER}":"${WHISPER_GROUP}" "${WHISPER_DATA_PATH}" ; fi

    if [ ! -d "${WHISPER_LOG_PATH}" ]; then
        mkdir -p "${WHISPER_LOG_PATH}"
    fi
    if [ $(stat -c %U "${WHISPER_LOG_PATH}") != "${WHISPER_USER}" ] ; then chown -R "${WHISPER_USER}":"${WHISPER_GROUP}" "${WHISPER_LOG_PATH}" ; fi

    case "${WHISPER_LOG_TYPE,,}" in
        file | both)
            create_logrotate whisper "${WHISPER_LOG_PATH}"/"${WHISPER_LOG_FILE}" whisper "${WHISPER_USER}" "${WHISPER_GROUP}"
        ;;
    esac
}