#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/10-wyoming
prepare_service

PROCESS_NAME="wyoming"

cat <<EOF

***********************************************************************************************
*                                                                                             *
*                    END OF LIFE NOTICE OCTOBER 09, 2025                                      *
*                               tiredofit/wyoming                                             *
*                                                                                             *
* This image is no longer maintained as of and will not receive updates.                      *
*                                                                                             *
* A successor image is available at:                                                          *
*                                                                                             *
* Repository | Documentation:                                                                 *
*   - https://github.com/nfrastack/container-wyoming                                          *
*                                                                                             *
* Image Registries:                                                                           *
*   - https://hub.docker.com/r/nfrastack/wyoming                                              *
*   - https://github.com/nfrastack/container-moodle/pkgs/container/container-wyoming          *
*                                                                                             *
* Please visit https://nfrastack.com for more information.                                    *
*                                                                                             *
***********************************************************************************************

EOF

sleep 15
setup_container_mode

liftoff
