#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/10-wyoming
source /assets/functions/10-wyoming
source /tmp/.container/wyoming/.mode-env
PROCESS_NAME="piper"

if [ ! -f "/tmp/.container/container-restart" ] ; then
    if var_true "${ENABLE_PIPER}" ; then
        print_debug "Configuring Piper"
        source /assets/defaults/30-piper
        source /assets/functions/30-piper
        piper_bootstrap_filesystem
        print_debug "Finished Configuring Piper"
    else
        service_stop 30-piper
    fi
fi

liftoff
