#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/10-wyoming
source /assets/functions/10-wyoming
source /tmp/.container/wyoming/.mode-env
PROCESS_NAME="whisper"

if [ ! -f "/tmp/.container/container-restart" ] ; then
    if var_true "${ENABLE_WHISPER}" ; then
        print_debug "Configuring Whisper"
        source /assets/defaults/40-whisper
        source /assets/functions/40-whisper
        whisper_bootstrap_filesystem
        print_debug "Finished Configuring Whisper"
    else
        service_stop 40-whisper
    fi
fi

liftoff
