#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/10-wyoming
source /container/functions/10-wyoming
source /container/state/wyoming/mode
SERVICE_NAME="piper"

if check_container_restarted ; then
    if var_true "${ENABLE_PIPER}" ; then
        print_debug "Configuring Piper"
        source /container/defaults/30-piper
        source /container/functions/30-piper
        piper_bootstrap_filesystem
        print_debug "Finished Configuring Piper"
    else
        service_stop 30-piper
    fi
fi

liftoff
