services:
  wyoming-app:
    image: docker.io/nfrastack/wyoming
    container_name: wyoming-app
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - MODE=ALL
    networks:
      - services
    restart: always

networks:
  services:
    external: true
