#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="whisper"
prepare_service defaults

check_container_initialized
check_service_initialized init


case "${WHISPER_LISTEN_TYPE,,}" in
    tcp )
        whisper_listen="tcp://${WHISPER_LISTEN_IP}:${WHISPER_LISTEN_PORT}"
    ;;
esac

case "${WHISPER_LOG_LEVEL,,}" in
    debug )
        whisper_loglevel="--debug"
    ;;
esac

case "${WHISPER_LOG_TYPE,,}" in
    both )
        SHOW_OUTPUT=TRUE
        touch "${WHISPER_LOG_PATH%/}"/"${WHISPER_LOG_FILE}"
        chown -R "${WHISPER_USER}" "${WHISPER_LOG_PATH%/}"/"${LOG_FILE}"
    ;;
    console )
        SHOW_OUTPUT=TRUE
        LOG_PATH=/dev
        LOG_FILE=/null
    ;;
    file )
        SHOW_OUTPUT=FALSE
        touch "${WHISPER_LOG_PATH%/}"/"${WHISPER_LOG_FILE}"
        chown -R "${WHISPER_USER}" "${WHISPER_LOG_PATH%/}"/"${WHISPER_LOG_FILE}"
    ;;
    none )
        SHOW_OUTPUT=FALSE
        LOG_PATH=/dev
        LOG_FILE=null
    ;;
esac

if [ -n "${WHISPER_INITIAL_PROMPT}" ]; then whisper_initial_prompt="${WHISPER_INITIAL_PROMPT}" ; fi
liftoff

print_start "Starting Whisper $(grep -o "ADD: Whisper .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
source /opt/"${WHISPER_USER}"/bin/activate
cd /opt/"${WHISPER_USER}"/bin
exec sudo -u "${WHISPER_USER}"  \
                                /opt/"${WHISPER_USER}"/bin/python \
                                        -m wyoming_faster_whisper \
                                        ${whisper_loglevel} --uri "${whisper_listen}" \
                                        --data-dir "${WHISPER_DATA_PATH}" \
                                        --model "${WHISPER_MODEL}" \
                                        --beam-size "${WHISPER_BEAM_SIZE}" \
                                        --language "${WHISPER_LANGUAGE,,}" \
                                        ${whisper_initial_prompt} --device "${WHISPER_DEVICE,,}" 2>&1 1>> "${WHISPER_LOG_PATH%/}"/"${WHISPER_LOG_FILE}" |  silent sudo -u "${WHISPER_USER}" tee -a "${WHISPER_LOG_PATH%/}"/"${WHISPER_LOG_FILE}"
